# Generated by Django 4.2.30 on 2026-06-18 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_study', models.CharField(blank=True, default='', max_length=200)),
                ('gpa', models.FloatField(default=0.0)),
                ('budget', models.FloatField(default=999999.0)),
                ('interests', models.CharField(blank=True, default='', max_length=500)),
                ('career_goals', models.TextField(blank=True, default='')),
                ('countries', models.TextField(blank=True, default='[]')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
